# Generated by Django 4.1.4 on 2022-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Если данное изображение привязано к объекту "Место", будет показано имя объекта. В противном случае, будет показан данный текст',
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="Файл изображения"),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Если не указан, будет сортирован автоматически",
                        null=True,
                        verbose_name="Порядковый номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сопроводительное изображение",
                "verbose_name_plural": "Сопроводительные изображения",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="place",
                to="places.placeimage",
                verbose_name="Картинки",
            ),
        ),
    ]
