# Generated by Django 4.1.4 on 2022-12-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_placeimage_place_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="images",
        ),
        migrations.AddField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="places.place",
                verbose_name="Место",
            ),
        ),
    ]
