# Generated by Django 4.1.4 on 2022-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_remove_place_images_placeimage_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ("order",),
                "verbose_name": "Сопроводительное изображение",
                "verbose_name_plural": "Сопроводительные изображения",
            },
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                default=0,
                help_text="Если не указан, будет сортирован автоматически",
                null=True,
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
