# Generated by Django 4.1.4 on 2022-12-15 15:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_placeimage_options_alter_placeimage_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Длинное описание"),
        ),
    ]
