# Generated by Django 4.1.4 on 2023-01-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_placeimage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placeimage",
            unique_together={("image", "place", "order")},
        ),
        migrations.RemoveField(
            model_name="placeimage",
            name="title",
        ),
    ]
