# Generated by Django 4.1.4 on 2023-01-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_alter_placeimage_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeimage",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                default=0,
                help_text="Если не указан, будет сортирован автоматически",
                verbose_name="Порядковый номер",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Место",
            ),
        ),
    ]
