# Generated by Django 4.1.4 on 2023-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_alter_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.TextField(verbose_name="Короткое описание"),
        ),
    ]
